action_server: 'rcom/RCoM_ActionServer'
control_client: 'PositionJointInterface_trajectory_controller/follow_joint_trajectory'
planning_group: 'arm_endoscope'

# gains
kt: [0.1,0.1,0.1,0.1]
krcm: [0.2, 0.2, 0.2]
lambda0: 0.5

# control interval
dt: 0.01

# velocity scaling
alpha: 1.0

# link names
link_pi: 'storz_endoscope_link_1'
link_pip1: 'storz_endoscope_link_cm'

# threshold 1, divergence check prior to execution
t1_td: 0.1
t1_p_trocar: 0.01

# threshold 2, convergence check after execution
t2_td: 0.001
t2_p_trocar: 0.01

# threshold scale
t_td_scale: [1.0, 1.0, 1.0, 0.1]

# max number of iterations
max_iter: 20
