action_server: 'RCoM_ActionServer'
control_client: 'PositionJointInterface_trajectory_controller/follow_joint_trajectory'
planning_group: 'arm_endoscope'

# gains
kt: [1.0, 1.0, 1.0]
krcm: 0.5
lambda0: 0.5

# control interval
dt: 0.1

# velocity scaling
alpha: 1.0

# link names
link_pi: 'endoscope_link_1'
link_pip1: 'endoscope_link_cm'

# threshold 1
t1_td: 0.1
t1_p_trocar: 0.1

# threshold 2
t2_td: 0.01
t2_p_trocar: 0.01
max_iter: 20
